name: jspaint
icon: snap/gui/icon.png
adopt-info: jspaint
summary: Classic MS Paint clone with extra features
description: |
  Classic MS Paint clone with extra features
base: core18
grade: stable
confinement: strict

apps:
  jspaint:
    command: jspaint
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - alsa
      - avahi-observe
      - browser-support
      - camera
      - cups-control
      - gsettings
      - home
      - network
      - opengl
      - audio-playback
      - screen-inhibit-control
      - upower-observe

parts:    
  jspaint:
    plugin: nil
    override-build: |
      set -eu
      
      curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      apt remove cmdtest
      apt update && apt install -y --no-install-recommends nodejs yarn
      git clone https://github.com/1j01/jspaint.git --depth 1
      cd jspaint
      VERSION=$(jq . package.json | grep version | cut -d'"' -f4 | sed s'/v//' | head -n 1)
      echo $VERSION
      snapcraftctl set-version "$VERSION"
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE=
        export HTTP_PROXY=$http_proxy
        export HTTPS_PROXY=$https_proxy
      fi
      
      sed -i -e '/cypress/d' package.json
      sed -i -e '/ cy:/d' package.json
      sed -i -e '/debug/d' package.json
      sed -i -e '/serve/d' package.json
      sed -i -e '/electron-forge/d' package.json
      sed -i -e '/:NOTE/d' package.json

      yarn add electron-packager --dev
      ./node_modules/.bin/electron-packager ./ --electron-version=7.1.14 --asar --overwrite --out=./out

      mv out/* o/
      mv o/* $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/JS\ Paint $SNAPCRAFT_PART_INSTALL/jspaint

    build-packages:
      - jq
      - sed
      - git
      - curl
      - unzip
    stage-packages:
      - libx11-xcb1
      - libx11-6
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - libasound2
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libcups2
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango1.0-0
      - libpangocairo-1.0-0
      - libxcb1
